# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Mod properties
mod_version = 1.0.0
maven_group = com.infamous
archives_name = dungeons_mobs_legacy

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
neoforge_version = 21.1.243

# Libraries
curios_version=9.5.1+1.21.1
geckolib_version=4.9.2

# Extras
dungeons_gear_version=1.19.2-5.0.5-beta
illagers_wear_armor_version=5538877
enchant_with_mob_version=8491228

jei_version=19.39.0.371
jer_version=5057220
jeed_version=6172935

rei_version=9.1.580
rer_version=3929213

architectury_version=9.2.14
cloth_config_version=11.1.136

configured_version=7276577
catalogue_version=4766090

appleskin_version=4770828

mob_battle_version=6596542

spark_version=4738952