# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = forge

# Mod properties
mod_version = 1.0.0
maven_group = com.infamous
archives_name = dungeons_mobs_legacy

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
forge_version = 1.20.1-47.4.10

# Libraries
curios_version=5.14.1+1.20.1
geckolib_version=4.7.4

# Extras
dungeons_gear_version=1.19.2-5.0.5-beta
illagers_wear_armor_version=5538877
enchant_with_mob_version=6593792

jei_version=15.20.0.112
jer_version=5057220
jeed_version=6172935

rei_version=9.1.580
rer_version=3929213

architectury_version=9.2.14
cloth_config_version=11.1.136

configured_version=5180902
catalogue_version=4766090

appleskin_version=4770828

mob_battle_version=6596542

spark_version=4738952