modLoader="javafml" 
loaderVersion="[4,)"
license="MIT License"
issueTrackerURL="https://github.com/cassiancc/Dungeons-Mobs"

[[mods]]
modId="dungeons_mobs"
version="${version}"
displayName="Dungeons Mobs: Legacy"
# updateJSONURL="http://myurl.me/" 
# displayURL="http://example.com/"
logoFile="logo.png"
credits="Infamous Mods"
authors="the_infamous_1, cassiancc"
description='''
A port of Minecraft: Dungeons mobs to Minecraft: Java Edition, updated to 1.21.1.
'''
[[mods]]
modId="dungeons_libraries" #mandatory
version="${version}" #mandatory
displayName="Dungeons Libraries" #mandatory
logoFile="logo.png"
credits="" #optional
authors="the_infamous_1, Patrigan, cassiancc" #optional
description='''Library mod for the Dungeons Suite. Brings a lot of tools for modmakers to spice up their combat.'''

[[dependencies.dungeons_mobs]] 
    modId="neoforge"
    type="required" 
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]]
    modId="geckolib"
    type="required"
    versionRange="[4.7.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]]
    modId="curios"
    type="optional"
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="enchantwithmob" 
    type="optional"
    versionRange="[1.19.2-7.0.1,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="jei" 
    type="optional"
    versionRange="[11.2.0.247,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="justenoughresources" 
    type="optional"
    versionRange="[1.2.1.189,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="jeed" 
    type="optional"
    versionRange="[1.18,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="roughlyenoughitems" 
    type="optional"
    versionRange="[9.1.580,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="roughlyenoughresources" 
    type="optional"
    versionRange="[2.5.2,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="architectury" 
    type="optional"
    versionRange="[6.4.62,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="clothconfig" 
    type="optional"
    versionRange="[8.2.88,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="configured" 
    type="optional"
    versionRange="[2.0.1,)" 
    ordering="NONE"
    side="CLIENT"

[[dependencies.dungeons_mobs]] 
    modId="catalogue" 
    type="optional"
    versionRange="[1.7.0,)" 
    ordering="NONE"
    side="CLIENT"

[[dependencies.dungeons_mobs]] 
    modId="appleskin" 
    type="optional"
    versionRange="[2.4.2,)" 
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config='dungeons_mobs.mixins.json'

[[mixins]]
config='dungeons_libraries.mixins.json'